url: "https://ziyyueyu-c.github.io" # 替换为您站点的 URL
baseurl: "" # 如果您的站点位于子路径中，请在这里指定，例如 "/blog"

title: "Ziyue Yu | Curry" # 站点的标题
description: "Hello! This is Ziyue Yu!" # 站点的描述

# 主题设置
theme: jekyll-theme-primer # 主题名称，确保已在项目中安装

# Markdown 处理方式
markdown: kramdown
highlighter: rouge

# 插件设置
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Excluded files and directories (可以根据需要调整)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
