url: "https://ziyyueyu-c.github.io" # 站点的 URL
baseurl: "" # 站点位于根路径

title: "Ziyue Yu | Curry" # 站点标题
description: "Hello! This is Ziyue Yu!" # 站点描述

# 主题设置
theme: jekyll-theme-primer # 确保主题已安装

# Markdown 处理方式
markdown: kramdown
highlighter: rouge

# 插件设置
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 排除的文件和目录
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Sass 编译设置（如果需要）
sass:
  sass_dir: _sass
