menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}


social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

    contacts:
  - name: 'Ziyue Yu'
    title: 'Ph.D candidate'
    department: 'Civil and Environmental Engineering'
    institution: "Haven't been done"
    institution_address: 'NAN, Canada'
    phone: '(000) 000-0000'
    email: 'yuziyue020619@gmail.com'
    office: 'NAN'
    image: 'assets/img/contact.jpg'

