menu:
  - name: 'memory'
    url: '/memory'
  - name: 'publications'
    url: '/publications'
  - name: 'courses'
    url: '/courses'
  - name: 'cv'
    url: '/cv'
  - name: 'contact'
    url: '/contact'

contacts:
  - name: 'Ziyue Yu'
    title: 'Ph.D candidate'
    department: 'Civil and Environmental Engineering'
    institution: 'University of Pittsburgh'
    institution_address: "3700 O'Hara St, Pittsburgh, PA 15213"
    phone: '(412) 909 9999'
    email: '@outlook.com'
    office: '700 Benedum Hall'
    image: 'assets/img/1 (7).jpg'

courses:
  - name: "Fluid Mechanics"

publications:
  - title: '[Low Reynold number with high energy flux by design alignment between stress by injection and background strain]'
    url: 'https://www.leifang.org/'
  - title: '[Lagraingin version Stokes numbers]'
    url: 'https://www.leifang.org/'

memory:
  - title: 'Sample Memory 1'
    url: '/memory/sample-memory-1'
  - title: 'Sample Memory 2'
    url: '/memory/sample-memory-2'

social:
  - icon: 'github'
    link: 'https://github.com/LeNPaul'
  - icon: 'twitter'
    link: 'https://twitter.com/paululele'
  - icon: 'instagram'
    link: 'https://instagram.com/paululele'
  - icon: 'linkedin'
    link: 'https://linkedin.com/in/lenpaul'
